services:
  server:
    build:
      context: ./control_plane
      dockerfile: Dockerfile
    container_name: server
    environment:
      - SERVICE_NAME=server
    privileged: true
    networks:
      - service_mesh
    volumes:
      - /tmp:/tmp
      - /sys/kernel:/sys/kernel:ro
      - /sys/fs/bpf/:/sys/fs/bpf/

  service-1:
    build:
      context: ./xdp_user_proxy
      dockerfile: Dockerfile
    container_name: service1
    environment:
      - SERVICE_NAME=service1
    privileged: true
    networks:
      - service_mesh
    volumes:
      - /tmp:/tmp
      - /sys/kernel:/sys/kernel:ro
      - /sys/fs/bpf/:/sys/fs/bpf/

  service-2:
    build:
      context: ./xdp_user_proxy
      dockerfile: Dockerfile
    container_name: service2
    environment:
      - SERVICE_NAME=service2
    privileged: true
    networks:
      - service_mesh
    volumes:
      - /tmp:/tmp
      - /sys/kernel:/sys/kernel:ro
      - /sys/fs/bpf/:/sys/fs/bpf/

  service-3:
    build:
      context: ./xdp_user_proxy
      dockerfile: Dockerfile
    container_name: service3
    environment:
      - SERVICE_NAME=service3
    privileged: true
    networks:
      - service_mesh
    volumes:
      - /tmp:/tmp
      - /sys/kernel:/sys/kernel:ro
      - /sys/fs/bpf/:/sys/fs/bpf/

networks:
  service_mesh:
    driver: bridge
